name: SurvivalCore
version: 1.0
main: site.ftka.survivalcore.MClass
description: Survival Core
author: srleg
api-version: '1.21'
commands:
  chat:
    description: run ChatManager app
  exitscreen:
    description: exit any screen the player is on
  server:
    description: run ServerAdministration app
    aliases: sv
  permissions:
    description: run PermissionsManager app
    aliases: p, perms