name: SurvivalCore
version: 1.0
main: site.ftka.survivalcore.MClass
description: Survival Core
author: srleg
api-version: '1.20'
commands:
  server:
    description: run ServerAdministration app
    aliases: sv
    usage: /server